"" coc.nvim
let g:coc_global_extensions = [
  \'coc-tsserver',
  \'coc-eslint8',
  \'coc-prettier',
  \'coc-git',
  \'coc-go',
  \'coc-lua',
  \'coc-pyright',
  \'coc-json',
  \'coc-java',
  \'coc-markdownlint',
  \'coc-toml',
  \'coc-yaml',
  \'coc-kotlin',
  \'coc-html',
  \'coc-clangd',
  \'coc-phpls',
  \'coc-sql',
  \'coc-julia',
  \'coc-docker',
  \'coc-pydocstring',
  \'coc-rust-analyzer',
  \'coc-fzf-preview',
  \'coc-lists'
\]
