# ============================================================================
# Machine-Specific Fish Configuration: MacBook Pro M3 Max
# Computer Name: 9dw-main01-m3max-macbookpro (hostname: Mac)
# Generated by: Trinitas System (Artemis Optimization)
# Date: 2025-11-13, Updated: 2025-11-17
# Purpose: MacBook Pro specific settings and personal functions
# ============================================================================

# ============================================================================
# macOS Build Dependencies
# ============================================================================
set -gx LDFLAGS "-L/opt/homebrew/opt/libxml2/lib"
set -gx CPPFLAGS "-I/opt/homebrew/opt/libxml2/include"
set -gx TESSDATA_PREFIX "/opt/homebrew/share/tessdata/"

# ============================================================================
# Homebrew Environment (Apple Silicon)
# ============================================================================
set -gx HOMEBREW_PREFIX "/opt/homebrew"
set -gx HOMEBREW_CELLAR "/opt/homebrew/Cellar"
set -gx HOMEBREW_REPOSITORY "/opt/homebrew"

# Homebrew PATH (managed by fish_add_path in main config)
# set -gx PATH "/opt/homebrew/bin" "/opt/homebrew/sbin" $PATH

# Homebrew manpages
set -q MANPATH; or set MANPATH ''
set -gx MANPATH "/opt/homebrew/share/man" $MANPATH

# Homebrew info pages
set -q INFOPATH; or set INFOPATH ''
set -gx INFOPATH "/opt/homebrew/share/info" $INFOPATH

# ============================================================================
# macOS-Specific Aliases
# ============================================================================
# Tailscale CLI
alias tailscale "/Applications/Tailscale.app/Contents/MacOS/Tailscale"

# exa (modern ls replacement)
if type -q exa
    alias ll "exa -l -g --icons"
    alias lla "ll -a"
end

# ============================================================================
# Conda/Miniforge Configuration (Machine-Specific)
# ============================================================================
# This machine uses Miniforge (conda) installed at ~/miniforge3
# Lazy initialization for faster shell startup (~50-100ms saved)
#
# Note: If you want base environment auto-activated, run:
#   conda config --set auto_activate_base true
# ============================================================================

set -gx CONDA_BASE "$HOME/miniforge3"

if test -d $CONDA_BASE
    # Set conda environment variables
    set -gx CONDA_EXE "$CONDA_BASE/bin/conda"
    set -gx _CONDA_ROOT "$CONDA_BASE"
    set -gx _CONDA_EXE "$CONDA_BASE/bin/conda"

    # Lazy-load conda on first use (saves ~50-100ms on shell startup)
    function conda --description "Lazy-loaded conda with auto-initialization"
        # Remove this wrapper function
        functions -e conda

        # Source the conda initialization script (the reliable method)
        if test -f "$_CONDA_ROOT/etc/fish/conf.d/conda.fish"
            source "$_CONDA_ROOT/etc/fish/conf.d/conda.fish"
        else
            # Fallback: add to PATH and define minimal conda function
            fish_add_path -gP "$_CONDA_ROOT/bin"
        end

        # Now call the real conda command with original arguments
        conda $argv
    end

    # Also lazy-load mamba if available
    if test -f "$CONDA_BASE/bin/mamba"
        function mamba --description "Lazy-loaded mamba"
            functions -e mamba
            if test -f "$_CONDA_ROOT/etc/fish/conf.d/mamba.fish"
                source "$_CONDA_ROOT/etc/fish/conf.d/mamba.fish"
            end
            mamba $argv
        end
    end
end

# ============================================================================
# Personal Functions
# ============================================================================

# Multi-host file transfer function
# Usage: transfer_files [-o] <source> <destination>
#   -o: Use "outside" network (default: "inside")
function transfer_files
    # Parse options
    set mode "inside"
    while test (count $argv) -gt 0
        switch $argv[1]
            case '-o'
                set mode "outside"
                set argv (echo $argv[2..-1])
            case '*'
                break
        end
    end

    # Validate arguments
    if test (count $argv) -lt 2
        echo "Usage: transfer_files [-o] <source> <destination>" >&2
        echo "  -o: Use outside network (default: inside)" >&2
        return 1
    end

    # Transfer parameters
    set source_path $argv[1]
    set destination_dir $argv[2]

    # Host list (personal network)
    set hosts \
        "9dw-main02-m2ultra-macpro-inside" \
        "9dw-macbook-promax-m2-inside" \
        "9dw-llm-dev01-inside" \
        "9dw-llm-dev02-inside" \
        "9dw-llm-dev03-inside"

    # Transfer to each host
    for host in $hosts
        set remote_host (string replace -r 'inside' $mode $host)
        echo "📤 Transferring $source_path to $remote_host:$destination_dir"
        scp -r $source_path $remote_host:$destination_dir

        if test $status -eq 0
            echo "  ✅ Success: $remote_host"
        else
            echo "  ❌ Failed: $remote_host" >&2
        end
    end

    echo "✓ Transfer complete."
end
