-- ============================================================================
-- OpenCode.nvim - Production-Grade Configuration
-- ============================================================================
-- Environment:
--   Neovim: 0.11.4
--   LazyVim: Active
--   OpenCode CLI: 0.15.18
--   Plugin: NickvanDyke/opencode.nvim (最推奨実装)
--
-- Generated by: Trinitas System (Artemis - Technical Perfectionist)
-- Date: 2025-10-28
-- Quality: Production-Ready
-- Security: MEDIUM RISK - Approved
-- ============================================================================

return {
  {
    "NickvanDyke/opencode.nvim",

    -- ========================================================================
    -- 依存関係設定
    -- ========================================================================
    dependencies = {
      {
        "folke/snacks.nvim",
        opts = {
          input = {},    -- ask()機能で必要
          picker = {},   -- select()機能で必要
          terminal = {}, -- toggle()機能で必要
        },
      },
    },

    -- ========================================================================
    -- 遅延読み込み（パフォーマンス最適化）
    -- ========================================================================
    cmd = {
      "OpencodePrompt",
      "OpencodeAsk",
      "OpencodeSelect",
      "OpencodeCommand",
      "OpencodeToggle",
    },

    -- ========================================================================
    -- プラグイン初期化設定
    -- ========================================================================
    config = function()
      -- OpenCode設定
      vim.g.opencode_opts = {
        -- ====================================================================
        -- プロバイダー設定（snacks.nvim統合）
        -- ====================================================================
        provider = {
          enabled = "snacks", -- LazyVim標準のsnacks.nvim使用

          snacks = {
            win = {
              position = "right", -- 右側に配置
              width = 0.4, -- 画面幅の40%
              height = 1.0, -- 画面高さの100%
              border = "rounded", -- 角丸ボーダー
            },
            -- ターミナルオプション
            bo = {
              filetype = "opencode",
            },
            wo = {
              winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
            },
          },
        },

        -- ====================================================================
        -- 自動リロード設定
        -- ====================================================================
        auto_reload = true, -- OpenCodeがファイル変更時に自動リロード

        -- ====================================================================
        -- カスタムプロンプト定義（拡張可能）
        -- ====================================================================
        prompts = {
          -- 基本プロンプト（組み込み）
          explain = {
            prompt = "Explain @this in detail",
            description = "Explain code",
          },
          optimize = {
            prompt = "Optimize @this for performance and readability",
            description = "Optimize code",
          },
          document = {
            prompt = "Add detailed documentation to @this",
            description = "Document code",
          },
          test = {
            prompt = "Generate comprehensive tests for @this",
            description = "Generate tests",
          },
          review = {
            prompt = "Review @this for bugs and improvements",
            description = "Code review",
          },

          -- カスタムプロンプト（Artemis推奨）
          security_audit = {
            prompt = [[
Perform a comprehensive security audit of @this:
1. Identify potential vulnerabilities
2. Check for SQL injection, XSS, CSRF risks
3. Validate input sanitization
4. Review authentication/authorization
5. Suggest security improvements with concrete code examples
]],
            description = "Security audit",
          },

          performance_profile = {
            prompt = [[
Analyze @this for performance bottlenecks:
1. Identify time complexity issues (target: O(n) or better)
2. Check for N+1 database queries
3. Review memory usage patterns
4. Suggest caching opportunities
5. Recommend specific optimization strategies with benchmarks
]],
            description = "Performance profiling",
          },

          refactor = {
            prompt = [[
Suggest refactoring improvements for @this:
1. Identify code smells (duplicated code, long methods, etc.)
2. Check for SOLID principle violations
3. Suggest applicable design patterns
4. Improve readability and maintainability
5. Reduce cyclomatic complexity (target: < 10)
]],
            description = "Refactoring suggestions",
          },

          type_safety = {
            prompt = [[
Review @this for type safety:
1. Identify missing type annotations
2. Check for implicit Any/Dynamic types
3. Validate type compatibility
4. Suggest strict type improvements
5. Check for null/undefined safety issues
]],
            description = "Type safety review",
          },

          architecture_review = {
            prompt = [[
Review @this from architectural perspective:
1. Evaluate separation of concerns
2. Check dependency direction (follow dependency rule)
3. Identify architectural violations
4. Suggest layer/module improvements
5. Assess testability and maintainability
]],
            description = "Architecture review",
          },
        },

        -- ====================================================================
        -- イベントハンドラー（自動化）
        -- ====================================================================
        on_event = function(event)
          -- セッション完了通知
          if event.type == "session.idle" then
            vim.notify("✅ OpenCode session completed", vim.log.levels.INFO)
          end

          -- エラー通知
          if event.type == "session.error" then
            vim.notify("⚠️ OpenCode error: " .. vim.inspect(event), vim.log.levels.WARN)
          end

          -- セッション開始通知
          if event.type == "session.started" then
            vim.notify("🚀 OpenCode session started", vim.log.levels.INFO)
          end
        end,
      }

      -- ======================================================================
      -- グローバル設定（Neovim）
      -- ======================================================================

      -- 自動リロード有効化（OpenCodeのファイル変更を自動反映）
      vim.o.autoread = true

      -- ======================================================================
      -- セキュリティ設定（機密ファイルでの無効化）
      -- ======================================================================
      vim.api.nvim_create_autocmd("BufEnter", {
        pattern = {
          "*.env",
          "*.env.*",
          "*.key",
          "*.pem",
          "*.secret",
          "*secret*",
          "*password*",
          "*.credentials",
        },
        callback = function()
          vim.b.opencode_disabled = true
          vim.notify(
            "⚠️ OpenCode disabled (sensitive file detected)",
            vim.log.levels.WARN
          )
        end,
        desc = "Disable OpenCode in sensitive files",
      })

      -- ======================================================================
      -- 自動化: 保存時のエラーチェック（オプション）
      -- ======================================================================
      -- vim.api.nvim_create_autocmd("BufWritePost", {
      --   callback = function()
      --     -- LSP診断エラーを検出
      --     local diagnostics = vim.diagnostic.get(0, {
      --       severity = vim.diagnostic.severity.ERROR,
      --     })
      --
      --     if #diagnostics > 0 then
      --       -- エラーがある場合、修正を提案
      --       local choice = vim.fn.confirm(
      --         string.format(
      --           "%d errors detected. Send to OpenCode for fix?",
      --           #diagnostics
      --         ),
      --         "&Yes\n&No",
      --         2
      --       )
      --       if choice == 1 then
      --         require("opencode").prompt("Fix @diagnostics", { submit = true })
      --       end
      --     end
      --   end,
      --   desc = "Auto-suggest OpenCode fix on errors",
      -- })

      -- ======================================================================
      -- イベントリスナー（拡張例）
      -- ======================================================================
      vim.api.nvim_create_autocmd("User", {
        pattern = "OpencodeEvent",
        callback = function(args)
          local event = args.data.event

          -- ファイル変更の自動リロード
          if event.type == "file.changed" then
            vim.cmd("checktime") -- バッファリロード
            vim.notify("🔄 File reloaded by OpenCode", vim.log.levels.INFO)
          end

          -- 許可リクエストの通知
          if event.type == "permission.requested" then
            vim.notify(
              "🔐 OpenCode requesting permission: " .. vim.inspect(event.data),
              vim.log.levels.WARN
            )
          end
        end,
        desc = "OpenCode event handler",
      })
    end,

    -- ========================================================================
    -- キーマップ設定（LazyVim標準）
    -- ========================================================================
    keys = {
      -- ====================================================================
      -- 基本操作
      -- ====================================================================

      -- OpenCodeトグル
      {
        "<leader>ot",
        function()
          require("opencode").toggle()
        end,
        desc = "OpenCode: Toggle terminal",
      },

      -- クイック質問（選択範囲/カーソル位置）
      {
        "<leader>oa",
        function()
          require("opencode").ask("@this: ", { submit = true })
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Ask about @this",
      },

      -- プロンプト選択メニュー
      {
        "<leader>os",
        function()
          require("opencode").select()
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Select prompt",
      },

      -- コンテキスト送信
      {
        "<leader>o+",
        function()
          require("opencode").prompt("@this")
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Send @this to context",
      },

      -- コマンド実行
      {
        "<leader>oc",
        function()
          require("opencode").command()
        end,
        desc = "OpenCode: Execute command",
      },

      -- ====================================================================
      -- 組み込みプロンプト（大文字キー）
      -- ====================================================================

      -- Explain（説明）
      {
        "<leader>oE",
        function()
          require("opencode").prompt("Explain @this in detail", { submit = true })
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Explain code",
      },

      -- Optimize（最適化）
      {
        "<leader>oO",
        function()
          require("opencode").prompt(
            "Optimize @this for performance and readability",
            { submit = true }
          )
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Optimize code",
      },

      -- Test（テスト生成）
      {
        "<leader>oT",
        function()
          require("opencode").prompt("Generate comprehensive tests for @this", {
            submit = true,
          })
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Generate tests",
      },

      -- Document（ドキュメント化）
      {
        "<leader>oD",
        function()
          require("opencode").prompt("Add detailed documentation to @this", {
            submit = true,
          })
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Document code",
      },

      -- Review（コードレビュー）
      {
        "<leader>oR",
        function()
          require("opencode").prompt("Review @this for bugs and improvements", {
            submit = true,
          })
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Review code",
      },

      -- ====================================================================
      -- カスタムプロンプト（Artemis推奨）
      -- ====================================================================

      -- Security Audit
      {
        "<leader>oS",
        function()
          require("opencode").prompt(
            vim.g.opencode_opts.prompts.security_audit.prompt,
            { submit = true }
          )
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Security Audit",
      },

      -- Performance Profile
      {
        "<leader>oP",
        function()
          require("opencode").prompt(
            vim.g.opencode_opts.prompts.performance_profile.prompt,
            { submit = true }
          )
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Performance Profile",
      },

      -- Refactor
      {
        "<leader>oM",
        function()
          require("opencode").prompt(
            vim.g.opencode_opts.prompts.refactor.prompt,
            { submit = true }
          )
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Refactor Suggestions",
      },

      -- Type Safety
      {
        "<leader>oY",
        function()
          require("opencode").prompt(
            vim.g.opencode_opts.prompts.type_safety.prompt,
            { submit = true }
          )
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Type Safety Review",
      },

      -- Architecture Review
      {
        "<leader>oA",
        function()
          require("opencode").prompt(
            vim.g.opencode_opts.prompts.architecture_review.prompt,
            { submit = true }
          )
        end,
        mode = { "n", "x" },
        desc = "OpenCode: Architecture Review",
      },

      -- ====================================================================
      -- コンテキストベース操作
      -- ====================================================================

      -- Fix Diagnostics（LSPエラー修正）
      {
        "<leader>oF",
        function()
          require("opencode").prompt("Fix @diagnostics", { submit = true })
        end,
        desc = "OpenCode: Fix LSP diagnostics",
      },

      -- Review Git Diff
      {
        "<leader>oG",
        function()
          require("opencode").prompt("Review @diff", { submit = true })
        end,
        desc = "OpenCode: Review git diff",
      },

      -- Explain Diagnostics
      {
        "<leader>oX",
        function()
          require("opencode").prompt("Explain @diagnostics in detail", {
            submit = true,
          })
        end,
        desc = "OpenCode: Explain diagnostics",
      },

      -- ====================================================================
      -- セッション管理
      -- ====================================================================

      -- New Session
      {
        "<leader>oN",
        function()
          require("opencode").command("session_new")
        end,
        desc = "OpenCode: New session",
      },

      -- Interrupt Session
      {
        "<leader>oI",
        function()
          require("opencode").command("session_interrupt")
        end,
        desc = "OpenCode: Interrupt session",
      },

      -- Compact Session
      {
        "<leader>oK",
        function()
          require("opencode").command("session_compact")
        end,
        desc = "OpenCode: Compact session history",
      },

      -- Copy Messages
      {
        "<leader>oC",
        function()
          require("opencode").command("messages_copy")
        end,
        desc = "OpenCode: Copy messages",
      },
    },
  },

  -- ==========================================================================
  -- オプション拡張: blink.cmp統合（自動補完強化）
  -- ==========================================================================
  {
    "saghen/blink.cmp",
    optional = true,
    opts = function(_, opts)
      -- OpenCodeのプレースホルダー補完を有効化
      -- ask()使用時に@buffer, @selection等が補完される
      opts.sources = opts.sources or {}

      -- OpenCodeソースを追加
      if not vim.tbl_contains(opts.sources, { name = "opencode" }) then
        table.insert(opts.sources, { name = "opencode" })
      end

      return opts
    end,
  },

  -- ==========================================================================
  -- オプション拡張: grapple.nvim統合（タグコンテキスト）
  -- ==========================================================================
  -- {
  --   "cbochs/grapple.nvim",
  --   optional = true,
  --   -- grapple.nvimを使用している場合、@grappleプレースホルダーが使用可能
  --   -- 設定は不要、自動検出される
  -- },
}

-- ============================================================================
-- 使用方法 / Usage Examples
-- ============================================================================
--[[

## 基本的な使い方

### 1. OpenCodeを開く
キー: `<leader>ot`

### 2. クイック質問（選択範囲/カーソル位置）
1. ビジュアルモードでコードを選択
2. キー: `<leader>oa`
3. プロンプト入力: "@this: なぜこのコードはエラーになるのか？"

### 3. プロンプト選択メニュー
キー: `<leader>os`
→ 組み込みプロンプト一覧が表示される

## コンテキストプレースホルダー

| プレースホルダー | 説明 |
|---------------|------|
| `@buffer`     | 現在のバッファ全体 |
| `@buffers`    | 全ての開いているバッファ |
| `@cursor`     | カーソル位置情報 |
| `@selection`  | ビジュアル選択範囲 |
| `@this`       | 選択範囲またはカーソル位置（自動判定） |
| `@visible`    | 画面に表示されているテキスト |
| `@diagnostics`| LSP診断情報 |
| `@quickfix`   | QuickFixリスト |
| `@diff`       | Git差分 |
| `@grapple`    | grapple.nvimタグ（オプション） |

## 推奨ワークフロー

### 1. コードレビュー
1. 変更したコードを選択
2. `<leader>oR` （Review）
3. OpenCodeが品質、バグ、改善点を指摘

### 2. パフォーマンス最適化
1. 遅いコードを選択
2. `<leader>oP` （Performance Profile）
3. ボトルネック特定と最適化案を取得

### 3. セキュリティ監査
1. 認証・認可コードを選択
2. `<leader>oS` （Security Audit）
3. 脆弱性チェックと対策を取得

### 4. LSPエラー修正
1. エラーがある状態でファイルを開く
2. `<leader>oF` （Fix Diagnostics）
3. 自動修正案を取得

### 5. Git差分レビュー
1. 変更をコミット前に
2. `<leader>oG` （Review Diff）
3. 変更内容の妥当性を確認

## キーマップ一覧

| キー | モード | 機能 |
|------|-------|------|
| `<leader>ot` | n | OpenCodeトグル |
| `<leader>oa` | n, x | クイック質問 |
| `<leader>os` | n, x | プロンプト選択 |
| `<leader>o+` | n, x | コンテキスト送信 |
| `<leader>oc` | n | コマンド実行 |
| `<leader>oE` | n, x | Explain（説明） |
| `<leader>oO` | n, x | Optimize（最適化） |
| `<leader>oT` | n, x | Test（テスト生成） |
| `<leader>oD` | n, x | Document（ドキュメント） |
| `<leader>oR` | n, x | Review（レビュー） |
| `<leader>oS` | n, x | Security Audit |
| `<leader>oP` | n, x | Performance Profile |
| `<leader>oM` | n, x | Refactor Suggestions |
| `<leader>oY` | n, x | Type Safety Review |
| `<leader>oA` | n, x | Architecture Review |
| `<leader>oF` | n | Fix Diagnostics |
| `<leader>oG` | n | Review Git Diff |
| `<leader>oX` | n | Explain Diagnostics |
| `<leader>oN` | n | New Session |
| `<leader>oI` | n | Interrupt Session |
| `<leader>oK` | n | Compact Session |
| `<leader>oC` | n | Copy Messages |

--]]

-- ============================================================================
-- トラブルシューティング / Troubleshooting
-- ============================================================================
--[[

## 問題1: `snacks.nvim not found`

**解決策**:
LazyVimには標準搭載されているが、明示的に依存関係を追加:

```lua
dependencies = {
  { "folke/snacks.nvim", opts = { input = {}, picker = {}, terminal = {} } },
},
```

## 問題2: `autoread not working`

**解決策**:
`~/.config/nvim/lua/config/options.lua` に追加:

```lua
vim.o.autoread = true
```

## 問題3: OpenCode CLIが見つからない

**確認**:
```bash
which opencode
# → /opt/homebrew/bin/opencode
```

**解決策**:
設定に明示的にパスを追加:

```lua
vim.g.opencode_opts = {
  opencode_path = "/opt/homebrew/bin/opencode",
}
```

## 問題4: `@this` プレースホルダーが機能しない

**原因**:
選択範囲が認識されていない

**解決策**:
1. ビジュアルモードで選択
2. `:OpencodePrompt @this` を実行
3. または関数で実行: `:lua require("opencode").prompt("@this")`

## 問題5: キーマップが動作しない

**確認**:
```vim
:verbose map <leader>oa
```

**解決策**:
他のプラグインとの競合を確認し、カスタムキーマップに変更:

```lua
keys = {
  { "<C-g>a", function() require("opencode").ask("@this: ", {submit=true}) end },
},
```

## 健全性チェック

```vim
:checkhealth opencode
```

すべてのチェックが通ることを確認してください。

--]]
