-- ============================================================================
-- Wezterm Configuration - Generated by Trinitas System
-- Date: 2025-10-27
-- Version: 1.0
--
-- Features:
--   - Dracula Theme (Official)
--   - Custom background image with HSB adjustment
--   - PlemolJP Console NF font (size 14)
--   - Tab bar hidden (tmux-first approach)
--   - GPU acceleration (WebGpu)
--   - Performance optimizations for tmux
-- ============================================================================

local wezterm = require('wezterm')
local config = wezterm.config_builder()

-- ============================================================================
-- パフォーマンス最適化設定
-- ============================================================================

-- GPU加速を最大限活用（Apple Silicon最適化）
config.front_end = "WebGpu"
config.webgpu_power_preference = "HighPerformance"

-- アニメーションを最小化してレスポンス向上
config.animation_fps = 1
config.cursor_blink_ease_in = "Constant"
config.cursor_blink_ease_out = "Constant"

-- スクロールバックバッファの設定
config.scrollback_lines = 10000

-- 不要な機能を無効化
config.check_for_updates = false
-- Note: show_update_window is deprecated and removed (as of Wezterm 20250101+)

-- ============================================================================
-- Draculaテーマ設定（ビルトイン公式版）
-- ============================================================================

config.color_scheme = "Dracula"

-- ============================================================================
-- フォント設定（PlemolJP Console NF）
-- ============================================================================

config.font = wezterm.font_with_fallback({
  {
    family = "PlemolJP Console NF",
    weight = "Regular",
    harfbuzz_features = { "calt=1", "clig=1", "liga=1" },  -- リガチャ有効化
  },
  "JetBrains Mono",      -- フォールバック1
  "Noto Sans CJK JP",    -- 日本語フォールバック
})

config.font_size = 14.0
config.line_height = 1.2  -- 読みやすさとパフォーマンスのバランス

-- フォントレンダリング最適化
config.freetype_load_target = "Normal"
config.freetype_render_target = "Normal"

-- ============================================================================
-- 背景画像設定（縦横比保持、中央揃え）
-- ============================================================================
-- NOTE: Background image is configured in local.lua (machine-specific)

-- ============================================================================
-- ウィンドウ設定
-- ============================================================================

-- ウィンドウ装飾（標準的なウィンドウボタンを表示）
-- "RESIZE" → ボタン非表示、"TITLE|RESIZE" → ボタン表示
config.window_decorations = "TITLE | RESIZE"

-- ウィンドウパディング
config.window_padding = {
  left = 8,
  right = 8,
  top = 8,
  bottom = 8,
}

-- 起動時に最大化
wezterm.on("gui-startup", function(cmd)
  local tab, pane, window = wezterm.mux.spawn_window(cmd or {})
  window:gui_window():maximize()
end)

-- ============================================================================
-- タブバー設定（モダン＆シャープなデザイン）
-- ============================================================================

-- タブバーを表示
config.enable_tab_bar = true

-- カスタマイズ可能なタブバーを使用（シャープなデザインのため）
config.use_fancy_tab_bar = false

-- タブバーのスタイル設定
config.tab_bar_at_bottom = false  -- タブバーを上部に配置

-- タブが1つの時はタブバーを隠す（最大化時の画面スペース節約）
config.hide_tab_bar_if_only_one_tab = true

-- タブの最大幅
config.tab_max_width = 32

-- ============================================================================
-- tmux統合最適化
-- ============================================================================

-- スクロールバー無効化（tmuxのスクロール機能を使用）
config.enable_scroll_bar = false

-- ============================================================================
-- キーバインド設定
-- ============================================================================

config.keys = {
  -- Cmd+K でスクロールバックをクリア（macOS標準）
  {
    key = "k",
    mods = "CMD",
    action = wezterm.action.ClearScrollback("ScrollbackAndViewport"),
  },
  -- Cmd+T で新しいタブ（タブバー非表示でも機能）
  {
    key = "t",
    mods = "CMD",
    action = wezterm.action.SpawnTab("CurrentPaneDomain"),
  },
  -- tmux prefix (Ctrl-b) を保護
  {
    key = "b",
    mods = "CTRL",
    action = wezterm.action.SendKey { key = "b", mods = "CTRL" },
  },
}

-- ============================================================================
-- ベル設定
-- ============================================================================

-- ベルを完全に無効化
config.audible_bell = "Disabled"
config.visual_bell = {
  fade_in_duration_ms = 0,
  fade_out_duration_ms = 0,
}

-- ============================================================================
-- その他の設定
-- ============================================================================

-- 設定ファイルの自動リロード
config.automatically_reload_config = true

-- デフォルトシェルの設定（オプション）
-- config.default_prog = { "/bin/zsh", "-l" }

-- tmux自動起動（オプション - 必要に応じてコメント解除）
-- config.default_prog = { "/bin/zsh", "-l", "-c", "tmux new-session -As main" }

-- ============================================================================
-- タブデザイン（Draculaテーマ + 背景画像透過）
-- ============================================================================

-- タブバーの基本設定
config.colors = {
  tab_bar = {
    inactive_tab_edge = "none",  -- タブ間の境界線を非表示
    background = 'rgba(0, 0, 0, 0)',  -- 完全透明（背景画像を表示）
  },
}

-- ウィンドウフレーム設定（背景画像を透過表示）
config.window_frame = {
  inactive_titlebar_bg = 'rgba(0, 0, 0, 0)',  -- 完全透明
  active_titlebar_bg = 'rgba(0, 0, 0, 0)',    -- 完全透明
  font = wezterm.font({ family = 'PlemolJP Console NF', weight = 'Bold' }),
  font_size = 12.0,
}

-- Nerd Fontsアイコン（三角形エッジ）
local SOLID_LEFT_ARROW = wezterm.nerdfonts.ple_lower_right_triangle
local SOLID_RIGHT_ARROW = wezterm.nerdfonts.ple_upper_left_triangle

-- タブタイトルのフォーマット（Draculaテーマカラー）
wezterm.on('format-tab-title', function(tab, tabs, panes, config, hover, max_width)
  -- デフォルトの色（非アクティブタブ - Dracula Current Line）
  local background = 'rgba(68, 71, 90, 0.8)'   -- #44475a with transparency
  local foreground = '#f8f8f2'                 -- Dracula foreground
  local edge_background = 'rgba(0, 0, 0, 0)'   -- 完全透明

  -- アクティブタブの色（Dracula Purple）
  if tab.is_active then
    background = 'rgba(189, 147, 249, 0.9)'    -- #bd93f9 with slight transparency
    foreground = '#282a36'                     -- Dracula background (dark text)
  elseif hover then
    background = 'rgba(98, 114, 164, 0.8)'     -- #6272a4 (Dracula comment) with transparency
    foreground = '#f8f8f2'
  end

  local edge_foreground = background

  -- タブタイトル（前後にスペースを追加）
  local title = '   ' .. wezterm.truncate_right(tab.active_pane.title, max_width - 1) .. '   '

  -- 三角形エッジのタブデザイン
  return {
    { Background = { Color = edge_background } },
    { Foreground = { Color = edge_foreground } },
    { Text = SOLID_LEFT_ARROW },  -- 左三角形
    { Background = { Color = background } },
    { Foreground = { Color = foreground } },
    { Text = title },
    { Background = { Color = edge_background } },
    { Foreground = { Color = edge_foreground } },
    { Text = SOLID_RIGHT_ARROW },  -- 右三角形
  }
end)

-- ============================================================================
-- Machine-Specific Configuration Loading
-- ============================================================================
-- Load local.lua for machine-specific settings (background, window size, etc.)
local local_config_path = wezterm.config_dir .. '/local.lua'

local function file_exists(path)
  local f = io.open(path, "r")
  if f then
    f:close()
    return true
  end
  return false
end

if file_exists(local_config_path) then
  local ok, local_config = pcall(dofile, local_config_path)
  if ok and local_config then
    -- Merge local config into main config
    for k, v in pairs(local_config) do
      config[k] = v
    end
    wezterm.log_info('Loaded machine-specific config from: ' .. local_config_path)
  else
    wezterm.log_error('Failed to load local config: ' .. tostring(local_config))
  end
else
  wezterm.log_warn('No local.lua found. Using default settings.')
  wezterm.log_warn('Create ' .. local_config_path .. ' for machine-specific configuration.')
end

return config
