-- ============================================================================
-- Wezterm Configuration - Generated by Trinitas System
-- Date: 2025-12-20
-- Version: 1.1
--
-- Features:
--   - Dracula Theme (Official)
--   - Custom background image with HSB adjustment
--   - PlemolJP Console NF font (size 14)
--   - Zellij auto-start with session selection (fzf)
--   - Window size/position memory (restored on restart)
--   - GPU acceleration (WebGpu)
--   - Performance optimizations
-- ============================================================================

local wezterm = require('wezterm')
local config = wezterm.config_builder()

-- ============================================================================
-- パフォーマンス最適化設定
-- ============================================================================

-- GPU加速を最大限活用（Apple Silicon最適化）
config.front_end = "WebGpu"
config.webgpu_power_preference = "HighPerformance"

-- アニメーションを最小化してレスポンス向上
config.animation_fps = 1
config.cursor_blink_ease_in = "Constant"
config.cursor_blink_ease_out = "Constant"

-- スクロールバックバッファの設定
config.scrollback_lines = 10000

-- 不要な機能を無効化
config.check_for_updates = false
-- Note: show_update_window is deprecated and removed (as of Wezterm 20250101+)

-- ============================================================================
-- Draculaテーマ設定（ビルトイン公式版）
-- ============================================================================

config.color_scheme = "Dracula"

-- ============================================================================
-- フォント設定（PlemolJP Console NF）
-- ============================================================================

config.font = wezterm.font_with_fallback({
  {
    family = "PlemolJP Console NF",  -- プライマリ: 日本語+NerdFont完全サポート
    weight = "Regular",
    harfbuzz_features = { "calt=1", "clig=1", "liga=1" },  -- リガチャ有効化
  },
  "Noto Sans CJK JP",  -- 最終フォールバック
})

config.font_size = 14.0
config.line_height = 1.2  -- 読みやすさとパフォーマンスのバランス

-- フォントレンダリング最適化
config.freetype_load_target = "Normal"
config.freetype_render_target = "Normal"

-- ============================================================================
-- 背景画像設定（縦横比保持、中央揃え）
-- ============================================================================
-- NOTE: Background image is configured in local.lua (machine-specific)

-- ============================================================================
-- ウィンドウ設定
-- ============================================================================

-- ウィンドウ装飾（標準的なウィンドウボタンを表示）
-- "RESIZE" → ボタン非表示、"TITLE|RESIZE" → ボタン表示
config.window_decorations = "TITLE | RESIZE"

-- ウィンドウパディング
config.window_padding = {
  left = 8,
  right = 8,
  top = 8,
  bottom = 8,
}

-- ============================================================================
-- ウィンドウサイズ記憶・復元
-- ============================================================================
-- 前回終了時のウィンドウサイズと位置を記憶して復元

-- ウィンドウ状態を保存するファイル
local window_state_file = wezterm.config_dir .. '/.window_state.json'

-- ウィンドウ状態を読み込む
local function load_window_state()
  local f = io.open(window_state_file, 'r')
  if f then
    local content = f:read('*all')
    f:close()
    local ok, state = pcall(wezterm.json_parse, content)
    if ok and state then
      return state
    end
  end
  return nil
end

-- ウィンドウ状態を保存
local function save_window_state(window)
  local dims = window:get_dimensions()
  local state = {
    width = dims.pixel_width,
    height = dims.pixel_height,
    x = dims.left,
    y = dims.top,
    is_full_screen = dims.is_full_screen,
  }
  local f = io.open(window_state_file, 'w')
  if f then
    f:write(wezterm.json_encode(state))
    f:close()
  end
end

-- 起動時にウィンドウサイズを復元（または最大化）
wezterm.on("gui-startup", function(cmd)
  local state = load_window_state()
  local tab, pane, window = wezterm.mux.spawn_window(cmd or {})
  local gui_window = window:gui_window()

  if state then
    -- 保存されたサイズと位置を復元
    if state.is_full_screen then
      gui_window:maximize()
    else
      gui_window:set_position(state.x or 0, state.y or 0)
      gui_window:set_inner_size(state.width or 1200, state.height or 800)
    end
    wezterm.log_info('Restored window state from previous session')
  else
    -- 初回は最大化
    gui_window:maximize()
  end
end)

-- ウィンドウが閉じられる前に状態を保存
wezterm.on("window-resized", function(window, pane)
  save_window_state(window)
end)

-- ============================================================================
-- タブバー設定（モダン＆シャープなデザイン）
-- ============================================================================

-- タブバーを表示
config.enable_tab_bar = true

-- カスタマイズ可能なタブバーを使用（シャープなデザインのため）
config.use_fancy_tab_bar = false

-- タブバーのスタイル設定
config.tab_bar_at_bottom = false  -- タブバーを上部に配置

-- タブが1つの時はタブバーを隠す（最大化時の画面スペース節約）
config.hide_tab_bar_if_only_one_tab = true

-- タブの最大幅
config.tab_max_width = 32

-- ============================================================================
-- Zellij統合最適化
-- ============================================================================

-- スクロールバー無効化（Zellijのスクロール機能を使用）
config.enable_scroll_bar = false

-- ============================================================================
-- キーバインド設定 (Note: Full keybindings defined below in Zellij section)
-- ============================================================================
-- Keybindings are consolidated in the "Keybindings for Zellij Integration and Claude Code" section

-- ============================================================================
-- ベル設定
-- ============================================================================

-- ベルを完全に無効化
config.audible_bell = "Disabled"
config.visual_bell = {
  fade_in_duration_ms = 0,
  fade_out_duration_ms = 0,
}

-- ============================================================================
-- その他の設定
-- ============================================================================

-- 設定ファイルの自動リロード
config.automatically_reload_config = true

-- デフォルトシェルの設定（オプション）
-- config.default_prog = { "/bin/zsh", "-l" }


-- ============================================================================
-- タブデザイン（Draculaテーマ + 背景画像透過）
-- ============================================================================

-- タブバーの基本設定
config.colors = {
  tab_bar = {
    inactive_tab_edge = "none",  -- タブ間の境界線を非表示
    background = 'rgba(0, 0, 0, 0)',  -- 完全透明（背景画像を表示）
  },
}

-- ウィンドウフレーム設定（背景画像を透過表示）
config.window_frame = {
  inactive_titlebar_bg = 'rgba(0, 0, 0, 0)',  -- 完全透明
  active_titlebar_bg = 'rgba(0, 0, 0, 0)',    -- 完全透明
  font = wezterm.font({ family = 'PlemolJP Console NF', weight = 'Bold' }),
  font_size = 12.0,
}

-- Nerd Fontsアイコン（三角形エッジ）
local SOLID_LEFT_ARROW = wezterm.nerdfonts.ple_lower_right_triangle
local SOLID_RIGHT_ARROW = wezterm.nerdfonts.ple_upper_left_triangle

-- タブタイトルのフォーマット（Draculaテーマカラー）
wezterm.on('format-tab-title', function(tab, tabs, panes, config, hover, max_width)
  -- デフォルトの色（非アクティブタブ - Dracula Current Line）
  local background = 'rgba(68, 71, 90, 0.8)'   -- #44475a with transparency
  local foreground = '#f8f8f2'                 -- Dracula foreground
  local edge_background = 'rgba(0, 0, 0, 0)'   -- 完全透明

  -- アクティブタブの色（Dracula Purple）
  if tab.is_active then
    background = 'rgba(189, 147, 249, 0.9)'    -- #bd93f9 with slight transparency
    foreground = '#282a36'                     -- Dracula background (dark text)
  elseif hover then
    background = 'rgba(98, 114, 164, 0.8)'     -- #6272a4 (Dracula comment) with transparency
    foreground = '#f8f8f2'
  end

  local edge_foreground = background

  -- タブタイトル（前後にスペースを追加）
  local title = '   ' .. wezterm.truncate_right(tab.active_pane.title, max_width - 1) .. '   '

  -- 三角形エッジのタブデザイン
  return {
    { Background = { Color = edge_background } },
    { Foreground = { Color = edge_foreground } },
    { Text = SOLID_LEFT_ARROW },  -- 左三角形
    { Background = { Color = background } },
    { Foreground = { Color = foreground } },
    { Text = title },
    { Background = { Color = edge_background } },
    { Foreground = { Color = edge_foreground } },
    { Text = SOLID_RIGHT_ARROW },  -- 右三角形
  }
end)

-- ============================================================================
-- Zellij Integration (Terminal Multiplexer)
-- ============================================================================
-- Auto-start Zellij on Wezterm launch with session selection
--
-- Features:
--   - Session selection via fzf (if multiple sessions exist)
--   - Auto-attach if only one session exists
--   - Create new session if no sessions exist
--
-- Control via environment variable: WEZTERM_ZELLIJ_AUTO_START
--   - "true" or unset: Enable auto-start with session selection (default)
--   - "false": Disable auto-start
-- ============================================================================

-- Zellij session selector script (inline Fish)
local zellij_session_selector = [[
  set sessions (zellij list-sessions 2>/dev/null | string trim)

  if test -z "$sessions"
    # No sessions - create new one
    zellij
  else
    set session_count (echo "$sessions" | wc -l | string trim)

    if test "$session_count" -eq 1
      # Only one session - attach directly
      set session_name (echo "$sessions" | head -1 | awk '{print $1}')
      zellij attach "$session_name"
    else
      # Multiple sessions - use fzf to select
      set selected (echo "$sessions" | fzf --height=40% --reverse --header="Select Zellij Session (or Ctrl+C for new)")

      if test -n "$selected"
        set session_name (echo "$selected" | awk '{print $1}')
        zellij attach "$session_name"
      else
        # User cancelled - create new session
        zellij
      end
    end
  end
]]

-- Check if Zellij auto-start is enabled (default: true - 2025-12-20)
local zellij_auto_start = os.getenv('WEZTERM_ZELLIJ_AUTO_START')
if zellij_auto_start == nil then
  zellij_auto_start = 'true'  -- Default: enabled with session selection
end

-- Only auto-start if:
-- 1. Auto-start is enabled
-- 2. Not already inside a Zellij session (prevent nested sessions)
if zellij_auto_start:lower() ~= 'false' and os.getenv('ZELLIJ') == nil then
  -- Launch Fish with session selector script
  config.default_prog = { '/opt/homebrew/bin/fish', '-l', '-c', zellij_session_selector }

  wezterm.log_info('Zellij auto-start enabled with session selection.')
else
  if os.getenv('ZELLIJ') then
    wezterm.log_info('Already inside Zellij session. Skipping auto-start.')
  else
    wezterm.log_info('Zellij auto-start disabled via WEZTERM_ZELLIJ_AUTO_START.')
  end
end

-- ============================================================================
-- Keybindings (Consolidated)
-- ============================================================================
config.keys = {
  -- Cmd+K: Clear scrollback (macOS standard)
  {
    key = "k",
    mods = "CMD",
    action = wezterm.action.ClearScrollback("ScrollbackAndViewport"),
  },

  -- Cmd+T: New tab (works even when tab bar is hidden)
  {
    key = "t",
    mods = "CMD",
    action = wezterm.action.SpawnTab("CurrentPaneDomain"),
  },

  -- Ctrl+Alt+Z: Quick Zellij attach/launch
  -- CHANGED from Ctrl+z to Ctrl+Alt+z (Athena 2025-12-18): Avoid conflict with Neovim Undo
  {
    key = 'z',
    mods = 'CTRL|ALT',
    action = wezterm.action.SpawnCommandInNewTab {
      -- CRITICAL FIX (Artemis 2025-11-17): Use absolute path for keybinding
      args = { '/opt/homebrew/bin/zellij', 'attach', '--create' },
    },
  },

  -- Shift+Enter: Send newline character for Claude Code multi-line input
  -- FIX (2025-12-20): Alt+Enter conflicts with Wezterm, use Shift+Enter instead
  {
    key = 'Enter',
    mods = 'SHIFT',
    action = wezterm.action.SendString '\n',
  },

  -- Alt+Enter: Also map to newline for compatibility
  {
    key = 'Enter',
    mods = 'ALT',
    action = wezterm.action.SendString '\n',
  },
}

-- ============================================================================
-- Machine-Specific Configuration Loading
-- ============================================================================
-- Load local.lua for machine-specific settings (background, window size, etc.)
local local_config_path = wezterm.config_dir .. '/local.lua'

local function file_exists(path)
  local f = io.open(path, "r")
  if f then
    f:close()
    return true
  end
  return false
end

if file_exists(local_config_path) then
  local ok, local_config = pcall(dofile, local_config_path)
  if ok and local_config then
    -- Merge local config into main config
    for k, v in pairs(local_config) do
      config[k] = v
    end
    wezterm.log_info('Loaded machine-specific config from: ' .. local_config_path)
  else
    wezterm.log_error('Failed to load local config: ' .. tostring(local_config))
  end
else
  wezterm.log_warn('No local.lua found. Using default settings.')
  wezterm.log_warn('Create ' .. local_config_path .. ' for machine-specific configuration.')
end

return config
