#!/usr/bin/env bash
# ============================================================================
# installers/conda.sh - Miniforge3 (Conda)
# Purpose: Install Miniforge3 for Python environment management
# Platforms: macOS, Ubuntu
# ============================================================================

# Configuration
readonly CONDA_DIR="${HOME}/miniforge3"

# ============================================================================
# Main Installation
# ============================================================================

install_conda() {
    log_info "Installing Miniforge3..."

    # Install Miniforge3
    install_miniforge

    # Setup Fish integration (lazy-loading)
    setup_conda_fish

    log_success "Miniforge3 installation complete"
}

# ============================================================================
# Miniforge3 Installation
# ============================================================================

install_miniforge() {
    if [[ -d "${CONDA_DIR}" ]] && [[ -x "${CONDA_DIR}/bin/conda" ]]; then
        log_debug "Miniforge3 already installed at ${CONDA_DIR}"

        # Update conda
        log_info "Updating conda..."
        "${CONDA_DIR}/bin/conda" update -n base conda -y
        return 0
    fi

    log_info "Installing Miniforge3..."

    # Determine OS and architecture
    local os arch
    os=$(detect_os)
    arch=$(detect_arch)

    local platform=""
    case "${os}" in
        macos)
            platform="MacOSX"
            ;;
        ubuntu|debian|linux)
            platform="Linux"
            ;;
        *)
            log_error "Unsupported OS for Miniforge: ${os}"
            return 1
            ;;
    esac

    case "${arch}" in
        x86_64) arch="x86_64" ;;
        arm64|aarch64) arch="aarch64" ;;
        *)
            log_error "Unsupported architecture: ${arch}"
            return 1
            ;;
    esac

    # Special case: macOS uses arm64 not aarch64
    if [[ "${platform}" == "MacOSX" && "${arch}" == "aarch64" ]]; then
        arch="arm64"
    fi

    # Download Miniforge installer
    local installer_name="Miniforge3-${platform}-${arch}.sh"
    local installer_url="https://github.com/conda-forge/miniforge/releases/latest/download/${installer_name}"

    log_info "Downloading ${installer_name}..."

    local tmp_dir
    tmp_dir=$(mktemp -d)
    local installer_path="${tmp_dir}/${installer_name}"

    curl -fsSL "${installer_url}" -o "${installer_path}"

    if [[ ! -f "${installer_path}" ]]; then
        log_error "Failed to download Miniforge installer"
        rm -rf "${tmp_dir}"
        return 1
    fi

    # Run installer in batch mode
    log_info "Running Miniforge installer..."
    bash "${installer_path}" -b -p "${CONDA_DIR}"

    # Cleanup
    rm -rf "${tmp_dir}"

    # Verify installation
    if [[ -x "${CONDA_DIR}/bin/conda" ]]; then
        local version
        version=$("${CONDA_DIR}/bin/conda" --version 2>/dev/null)
        log_success "Miniforge3 installed: ${version}"
    else
        log_error "Miniforge installation failed"
        return 1
    fi
}

# ============================================================================
# Fish Shell Integration
# ============================================================================

setup_conda_fish() {
    log_info "Setting up Conda Fish integration..."

    # Check if machine-specific config already handles conda
    local machine_config="${HOME}/dotfiles/machines/${MACHINE_TYPE:-unknown}/fish.local.fish"
    if [[ -f "${machine_config}" ]]; then
        if grep -q "CONDA_BASE\|CONDA_EXE\|miniforge3" "${machine_config}" 2>/dev/null; then
            log_info "Conda configuration found in machine-specific config"
            log_debug "Skipping conf.d/conda.fish creation (${machine_config} handles it)"
            return 0
        fi
    fi

    local fish_conf_dir="${HOME}/.config/fish/conf.d"
    local conda_fish_file="${fish_conf_dir}/conda.fish"

    # Check if conf.d/conda.fish already exists
    if [[ -f "${conda_fish_file}" ]]; then
        log_debug "Conda Fish config already exists: ${conda_fish_file}"
        return 0
    fi

    mkdir -p "${fish_conf_dir}"

    log_info "Creating Conda Fish integration (lazy-loading)..."

    # Create Fish configuration with lazy-loading for faster startup
    cat > "${conda_fish_file}" << 'EOF'
# ============================================================================
# Conda (Miniforge3) Configuration for Fish
# Purpose: Lazy-loaded conda for faster shell startup
# Generated by dotfiles installer
# ============================================================================

set -l CONDA_BASE "$HOME/miniforge3"

if test -d $CONDA_BASE
    set -gx CONDA_EXE "$CONDA_BASE/bin/conda"
    set -gx _CONDA_ROOT $CONDA_BASE

    # Lazy-load conda on first use
    function conda --description "Lazy-loaded conda with auto-initialization"
        # Remove this wrapper
        functions -e conda

        # Initialize conda (hook doesn't accept arguments)
        if test -f $CONDA_EXE
            eval $CONDA_EXE "shell.fish" hook | source
        else if test -f "$_CONDA_ROOT/etc/fish/conf.d/conda.fish"
            source "$_CONDA_ROOT/etc/fish/conf.d/conda.fish"
        else
            fish_add_path -p "$_CONDA_ROOT/bin"
        end

        # Run the actual conda command with original arguments
        conda $argv
    end

    # Also provide mamba wrapper if mamba is available
    function mamba --description "Lazy-loaded mamba"
        # First ensure conda is initialized
        conda --version >/dev/null 2>&1

        # Then call mamba
        command mamba $argv
    end
end
EOF

    log_success "Conda Fish integration configured: ${conda_fish_file}"
}

# ============================================================================
# Verification
# ============================================================================

verify_conda() {
    local errors=0

    # Check conda
    if [[ -x "${CONDA_DIR}/bin/conda" ]]; then
        local version
        version=$("${CONDA_DIR}/bin/conda" --version 2>/dev/null)
        log_success "Conda installed: ${version}"
    else
        log_error "Conda not found at ${CONDA_DIR}"
        ((errors++))
    fi

    # Check mamba (included in Miniforge3)
    if [[ -x "${CONDA_DIR}/bin/mamba" ]]; then
        local version
        version=$("${CONDA_DIR}/bin/mamba" --version 2>/dev/null | head -1)
        log_success "Mamba installed: ${version}"
    else
        log_warn "Mamba not found (included in newer Miniforge3)"
    fi

    # Check Python
    if [[ -x "${CONDA_DIR}/bin/python" ]]; then
        local version
        version=$("${CONDA_DIR}/bin/python" --version 2>/dev/null)
        log_success "Python (base): ${version}"
    else
        log_warn "Python not found in base environment"
    fi

    return "${errors}"
}

# ============================================================================
# Utility Functions
# ============================================================================

# Update conda
update_conda() {
    log_info "Updating Conda..."

    if [[ -x "${CONDA_DIR}/bin/conda" ]]; then
        "${CONDA_DIR}/bin/conda" update -n base conda -y
        log_success "Conda updated"
    else
        log_error "Conda not found"
        return 1
    fi
}

# Create a new conda environment
create_conda_env() {
    local env_name="${1:-dev}"
    local python_version="${2:-3.12}"

    log_info "Creating conda environment: ${env_name} (Python ${python_version})..."

    if [[ -x "${CONDA_DIR}/bin/conda" ]]; then
        "${CONDA_DIR}/bin/conda" create -n "${env_name}" python="${python_version}" -y
        log_success "Environment '${env_name}' created"
    else
        log_error "Conda not found"
        return 1
    fi
}

# Initialize conda in current shell (for bash scripts)
init_conda_bash() {
    if [[ -f "${CONDA_DIR}/etc/profile.d/conda.sh" ]]; then
        source "${CONDA_DIR}/etc/profile.d/conda.sh"
    fi
}

# Clean conda cache
clean_conda() {
    log_info "Cleaning conda cache..."

    if [[ -x "${CONDA_DIR}/bin/conda" ]]; then
        "${CONDA_DIR}/bin/conda" clean --all -y
        log_success "Conda cache cleaned"
    fi
}

# Export functions
export -f install_conda install_miniforge setup_conda_fish verify_conda
export -f update_conda create_conda_env init_conda_bash clean_conda
