#!/usr/bin/env bash
# ============================================================================
# installers/golang.sh - Go Programming Language
# Purpose: Install Go with dynamic version detection
# Platforms: macOS (Homebrew), Ubuntu (official binary)
# ============================================================================

# Configuration
readonly GO_INSTALL_DIR="/usr/local/go"
readonly GOPATH_DIR="${HOME}/go"

# ============================================================================
# Main Installation
# ============================================================================

install_golang() {
    log_info "Installing Go..."

    case "${DETECTED_OS}" in
        macos)
            install_golang_macos
            ;;
        ubuntu|debian)
            install_golang_ubuntu
            ;;
        *)
            log_error "Go installation not supported on ${DETECTED_OS}"
            return 1
            ;;
    esac

    # Setup environment
    setup_golang_env

    # Setup Fish integration
    setup_golang_fish

    # Install ghq (Go-based tool)
    install_ghq_via_go

    log_success "Go installation complete"
}

# ============================================================================
# macOS Installation (Homebrew)
# ============================================================================

install_golang_macos() {
    if command_exists go; then
        local current_version
        current_version=$(go version | awk '{print $3}' | sed 's/go//')
        log_debug "Go already installed: ${current_version}"
        return 0
    fi

    log_info "Installing Go via Homebrew..."
    brew install go

    log_success "Go installed via Homebrew"
}

# ============================================================================
# Ubuntu Installation (Official Binary)
# ============================================================================

install_golang_ubuntu() {
    local current_version=""

    if command_exists go; then
        current_version=$(go version | awk '{print $3}' | sed 's/go//')
        log_debug "Go currently installed: ${current_version}"
    fi

    # Get latest version
    local latest_version
    latest_version=$(get_latest_go_version)

    log_info "Latest Go version: ${latest_version}"

    # Skip if already up to date
    if [[ "${current_version}" == "${latest_version}" ]]; then
        log_debug "Go is already up to date"
        return 0
    fi

    log_info "Installing Go ${latest_version}..."

    # Determine architecture
    local arch
    arch=$(detect_arch)

    case "${arch}" in
        x86_64) arch="amd64" ;;
        arm64|aarch64) arch="arm64" ;;
        *)
            log_error "Unsupported architecture: ${arch}"
            return 1
            ;;
    esac

    # Download URL
    local go_tarball="go${latest_version}.linux-${arch}.tar.gz"
    local go_url="https://go.dev/dl/${go_tarball}"

    # Remove existing installation
    if [[ -d "${GO_INSTALL_DIR}" ]]; then
        log_info "Removing existing Go installation..."
        sudo rm -rf "${GO_INSTALL_DIR}"
    fi

    # Download and extract
    log_info "Downloading ${go_tarball}..."
    local tmp_dir
    tmp_dir=$(mktemp -d)

    (
        cd "${tmp_dir}"
        curl -fsSLO "${go_url}"
        sudo tar -C /usr/local -xzf "${go_tarball}"
    )

    rm -rf "${tmp_dir}"

    log_success "Go ${latest_version} installed to ${GO_INSTALL_DIR}"
}

# ============================================================================
# Environment Setup
# ============================================================================

setup_golang_env() {
    log_info "Setting up Go environment..."

    # Create GOPATH directory structure
    mkdir -p "${GOPATH_DIR}"/{bin,pkg,src}

    log_debug "GOPATH created: ${GOPATH_DIR}"
}

# ============================================================================
# Fish Shell Integration
# ============================================================================

setup_golang_fish() {
    log_info "Setting up Go Fish integration..."

    local fish_conf_dir="${HOME}/.config/fish/conf.d"
    local go_fish_file="${fish_conf_dir}/golang.fish"

    # Check if golang.fish already exists
    if [[ -f "${go_fish_file}" ]]; then
        log_debug "Go Fish config already exists: ${go_fish_file}"
        return 0
    fi

    mkdir -p "${fish_conf_dir}"

    cat > "${go_fish_file}" << 'EOF'
# ============================================================================
# Go Programming Language Configuration for Fish
# Generated by dotfiles installer
# ============================================================================

# GOPATH
set -gx GOPATH "$HOME/go"

# Add Go binaries to PATH
# Check both locations: Homebrew (macOS) and standard (/usr/local/go)

# Standard Go installation
if test -d /usr/local/go/bin
    fish_add_path -p /usr/local/go/bin
end

# Homebrew Go (macOS)
if test -d /opt/homebrew/opt/go/bin
    fish_add_path -p /opt/homebrew/opt/go/bin
else if test -d /usr/local/opt/go/bin
    fish_add_path -p /usr/local/opt/go/bin
end

# GOPATH bin (go install destinations)
if test -d "$GOPATH/bin"
    fish_add_path -a "$GOPATH/bin"
end

# Go modules (default since Go 1.16)
set -gx GO111MODULE on

# Optional: Enable cgo
# set -gx CGO_ENABLED 1
EOF

    log_success "Go Fish integration configured: ${go_fish_file}"
}

# ============================================================================
# ghq Installation (Go-based tool)
# ============================================================================

install_ghq_via_go() {
    if command_exists ghq; then
        log_debug "ghq already installed"
        return 0
    fi

    # Ensure Go is in PATH
    if [[ -d "${GO_INSTALL_DIR}/bin" ]]; then
        export PATH="${GO_INSTALL_DIR}/bin:${PATH}"
    fi

    if ! command_exists go; then
        log_warn "Go not found, cannot install ghq"
        return 1
    fi

    log_info "Installing ghq via go install..."

    # Set GOPATH
    export GOPATH="${GOPATH_DIR}"
    export PATH="${GOPATH}/bin:${PATH}"

    go install github.com/x-motemen/ghq@latest

    if command_exists ghq || [[ -x "${GOPATH}/bin/ghq" ]]; then
        log_success "ghq installed successfully"
    else
        log_warn "ghq installation may have failed"
    fi
}

# ============================================================================
# Verification
# ============================================================================

verify_golang() {
    local errors=0

    # Check Go
    if command_exists go; then
        local version
        version=$(go version 2>/dev/null)
        log_success "Go installed: ${version}"
    else
        log_error "Go not found"
        ((errors++))
    fi

    # Check GOPATH
    if [[ -d "${GOPATH_DIR}" ]]; then
        log_success "GOPATH exists: ${GOPATH_DIR}"
    else
        log_warn "GOPATH not found"
    fi

    # Check ghq
    if command_exists ghq || [[ -x "${GOPATH_DIR}/bin/ghq" ]]; then
        log_success "ghq installed"
    else
        log_warn "ghq not found (optional)"
    fi

    return "${errors}"
}

# ============================================================================
# Utility Functions
# ============================================================================

# Update Go to latest version
update_golang() {
    log_info "Updating Go..."

    case "${DETECTED_OS}" in
        macos)
            brew upgrade go
            ;;
        ubuntu|debian)
            install_golang_ubuntu
            ;;
    esac

    log_success "Go updated to: $(go version)"
}

# Install common Go tools
install_go_tools() {
    log_info "Installing common Go tools..."

    local -a tools=(
        "golang.org/x/tools/gopls@latest"           # Language server
        "github.com/go-delve/delve/cmd/dlv@latest"  # Debugger
        "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"  # Linter
    )

    export GOPATH="${GOPATH_DIR}"
    export PATH="${GOPATH}/bin:${PATH}"

    for tool in "${tools[@]}"; do
        log_info "Installing ${tool}..."
        go install "${tool}"
    done

    log_success "Go tools installed"
}

# Export functions
export -f install_golang install_golang_macos install_golang_ubuntu
export -f setup_golang_env setup_golang_fish install_ghq_via_go
export -f verify_golang update_golang install_go_tools
