#!/usr/bin/env bash
# ============================================================================
# installers/rust.sh - Rust Programming Language
# Purpose: Install Rust via rustup
# Platforms: macOS, Ubuntu (cross-platform rustup)
# ============================================================================

# Configuration
readonly CARGO_HOME="${HOME}/.cargo"
readonly RUSTUP_HOME="${HOME}/.rustup"

# ============================================================================
# Main Installation
# ============================================================================

install_rust() {
    log_info "Installing Rust..."

    # Install rustup and stable toolchain
    install_rustup

    # Setup Fish integration
    setup_rust_fish

    # Install common tools
    install_rust_tools

    log_success "Rust installation complete"
}

# ============================================================================
# rustup Installation
# ============================================================================

install_rustup() {
    if command_exists rustup; then
        log_debug "rustup already installed"

        # Update to latest stable
        log_info "Updating Rust to latest stable..."
        rustup update stable
        return 0
    fi

    log_info "Installing Rust via rustup..."

    # Download and run rustup installer with default options
    # -y: Proceed without confirmation
    # --default-toolchain stable: Install stable toolchain
    # --profile default: Standard installation profile
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
        sh -s -- -y --default-toolchain stable --profile default

    # Verify installation
    if [[ -f "${CARGO_HOME}/env" ]]; then
        source "${CARGO_HOME}/env"
        log_success "Rust installed: $(rustc --version)"
    else
        log_error "Rust installation failed"
        return 1
    fi
}

# ============================================================================
# Fish Shell Integration
# ============================================================================

setup_rust_fish() {
    log_info "Setting up Rust Fish integration..."

    local fish_conf_dir="${HOME}/.config/fish/conf.d"
    local rust_fish_file="${fish_conf_dir}/rust.fish"

    # Check if rust.fish already exists
    if [[ -f "${rust_fish_file}" ]]; then
        log_debug "Rust Fish config already exists: ${rust_fish_file}"
        return 0
    fi

    # Check if config.fish already adds cargo bin to PATH
    local main_config="${HOME}/dotfiles/config/fish/config.fish"
    if [[ -f "${main_config}" ]]; then
        if grep -q "\.cargo/bin" "${main_config}" 2>/dev/null; then
            log_info "Cargo bin already in main config.fish PATH"
            log_debug "Skipping conf.d/rust.fish creation"
            return 0
        fi
    fi

    mkdir -p "${fish_conf_dir}"

    cat > "${rust_fish_file}" << 'EOF'
# ============================================================================
# Rust Programming Language Configuration for Fish
# Generated by dotfiles installer
# ============================================================================

# Cargo home
set -gx CARGO_HOME "$HOME/.cargo"

# Rustup home
set -gx RUSTUP_HOME "$HOME/.rustup"

# Add Cargo bin to PATH
if test -d "$CARGO_HOME/bin"
    fish_add_path -p "$CARGO_HOME/bin"
end

# Rust source path (for rust-analyzer)
# Updated automatically by rustup when rust-src component is installed
if test -d "$RUSTUP_HOME/toolchains/stable-"(uname -m)"-apple-darwin/lib/rustlib/src/rust/library"
    set -gx RUST_SRC_PATH "$RUSTUP_HOME/toolchains/stable-"(uname -m)"-apple-darwin/lib/rustlib/src/rust/library"
else if test -d "$RUSTUP_HOME/toolchains/stable-"(uname -m)"-unknown-linux-gnu/lib/rustlib/src/rust/library"
    set -gx RUST_SRC_PATH "$RUSTUP_HOME/toolchains/stable-"(uname -m)"-unknown-linux-gnu/lib/rustlib/src/rust/library"
end
EOF

    log_success "Rust Fish integration configured: ${rust_fish_file}"
}

# ============================================================================
# Rust Tools Installation
# ============================================================================

install_rust_tools() {
    log_info "Installing Rust tools..."

    # Source cargo env
    if [[ -f "${CARGO_HOME}/env" ]]; then
        source "${CARGO_HOME}/env"
    fi

    # Install components via rustup
    log_info "Installing rustup components..."
    rustup component add \
        rust-src \
        rust-analyzer \
        clippy \
        rustfmt

    # Install common cargo tools
    local -a cargo_tools=(
        "cargo-edit"      # cargo add/rm/upgrade
        "cargo-watch"     # Watch and rebuild
        "cargo-expand"    # Macro expansion
    )

    for tool in "${cargo_tools[@]}"; do
        if cargo install --list | grep -q "^${tool} "; then
            log_debug "${tool} already installed"
        else
            log_info "Installing ${tool}..."
            cargo install "${tool}" || log_warn "Failed to install ${tool} (optional)"
        fi
    done
}

# ============================================================================
# Verification
# ============================================================================

verify_rust() {
    local errors=0

    # Check rustup
    if command_exists rustup; then
        log_success "rustup installed"
    else
        log_error "rustup not found"
        ((errors++))
    fi

    # Check rustc
    if command_exists rustc; then
        local version
        version=$(rustc --version 2>/dev/null)
        log_success "Rust compiler: ${version}"
    else
        log_error "rustc not found"
        ((errors++))
    fi

    # Check cargo
    if command_exists cargo; then
        local version
        version=$(cargo --version 2>/dev/null)
        log_success "Cargo: ${version}"
    else
        log_error "cargo not found"
        ((errors++))
    fi

    # Check rust-analyzer
    if command_exists rust-analyzer; then
        log_success "rust-analyzer installed"
    else
        log_warn "rust-analyzer not found (optional)"
    fi

    return "${errors}"
}

# ============================================================================
# Utility Functions
# ============================================================================

# Update Rust toolchain
update_rust() {
    log_info "Updating Rust..."

    if [[ -f "${CARGO_HOME}/env" ]]; then
        source "${CARGO_HOME}/env"
    fi

    rustup update

    log_success "Rust updated to: $(rustc --version)"
}

# Install additional Rust toolchains
install_rust_toolchain() {
    local toolchain="${1:-nightly}"

    log_info "Installing Rust ${toolchain} toolchain..."

    if [[ -f "${CARGO_HOME}/env" ]]; then
        source "${CARGO_HOME}/env"
    fi

    rustup install "${toolchain}"
    log_success "Rust ${toolchain} toolchain installed"
}

# Setup Rust for cross-compilation
setup_rust_cross() {
    log_info "Setting up Rust cross-compilation..."

    if [[ -f "${CARGO_HOME}/env" ]]; then
        source "${CARGO_HOME}/env"
    fi

    # Common targets
    local -a targets=(
        "x86_64-unknown-linux-gnu"
        "aarch64-unknown-linux-gnu"
        "x86_64-apple-darwin"
        "aarch64-apple-darwin"
    )

    for target in "${targets[@]}"; do
        log_info "Adding target: ${target}"
        rustup target add "${target}" || log_warn "Could not add ${target}"
    done

    # Install cross for easier cross-compilation
    cargo install cross || log_warn "Could not install cross"

    log_success "Cross-compilation setup complete"
}

# Export functions
export -f install_rust install_rustup setup_rust_fish install_rust_tools
export -f verify_rust update_rust install_rust_toolchain setup_rust_cross
