-- ============================================================================
-- OpenCode.nvim Configuration (STABLE VERSION)
-- Generated by: Trinitas System (Hera + Artemis + Hestia)
-- Date: 2025-10-28
-- Plugin: NickvanDyke/opencode.nvim (推奨版)
--
-- Rationale:
--   - Better documentation and stability
--   - LazyVim native integration (snacks.nvim)
--   - Active development (804 GitHub stars)
--   - Comprehensive API and features
-- ============================================================================

return {
  {
    "NickvanDyke/opencode.nvim",

    -- Dependencies (snacks.nvim is already included in LazyVim)
    dependencies = {
      {
        "folke/snacks.nvim",
        opts = {
          input = {},
          picker = {},
        },
      },
    },

    -- Lazy loading commands
    cmd = {
      "Opencode",
      "OpencodeAddFile",
      "OpencodeRemoveFile",
      "OpencodeClose",
    },

    -- Configuration
    config = function()
      -- Global options
      vim.g.opencode_opts = {
        terminal_height = 20,
        auto_start = false,  -- Security: manual start only
      }

      -- Enable auto-reload for OpenCode changes
      vim.o.autoread = true

      -- Optional: Security logging
      vim.api.nvim_create_autocmd("User", {
        pattern = "OpencodeEvent",
        callback = function(args)
          if args.data and args.data.event == "started" then
            vim.notify("[OpenCode] Session started", vim.log.levels.INFO)
          end
        end,
      })
    end,

    -- Keymaps (LazyVim style)
    keys = {
      {
        "<leader>oc",
        "<cmd>Opencode<cr>",
        desc = "OpenCode: Open",
      },
      {
        "<leader>oa",
        "<cmd>OpencodeAddFile<cr>",
        desc = "OpenCode: Add File",
        mode = { "n", "v" },
      },
      {
        "<leader>or",
        "<cmd>OpencodeRemoveFile<cr>",
        desc = "OpenCode: Remove File",
      },
      {
        "<leader>ox",
        "<cmd>OpencodeClose<cr>",
        desc = "OpenCode: Close",
      },
    },
  },
}
